language: go
os: linux
go_import_path: github.com/redhat-developer/jenkins-operator

env:
  global:
    - GO111MODULE=on
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - KUBECONFIG=$HOME/.kube/config
    - secure: "VYyM5u6gu1ek2gm3auFdpXLOAMbmNoCAbEc1ehj0Gqm1Dy0fv4xJcAYEMwOeJGD3qaYRqI8eTKTNq+353xlIaJ0wIWD8z1xGKeU7mryrXcXRjl18cRwTl694B7mQEDjNU45tIFP8z6w7c4yrss/GaUHkdcidLcmqYFXHhCn28gTIsh5SEyZn3u4k8B91i2P1mqf1FmrE4Ausie//NJnWopD5FVSzpXWYAhyOGxtano2LeR8PrkuFyl+EP023vyvR2Fxok4u1WbcdOJNA4LJDUDfaNwCB07x3xrP9D/fWtPUPXowzHjWcOaDcxqnSHuAsJulGpkugFXL7VdXxkoYlL+rgkc9HUh1jUyemODjCAWMpKye1jHk+CGTJOoCwRmseNoUKFwsObpY+hFYjn8056zZMZ+U681P/dAKarbcUGVvLO9V9PWEKLbm5lVbCrbiajiFm7cCYVweN2iCf5dm0twVUYNvLg93p/f36zDRgiobxPmD5tmAdtbgknXE5l94OBX6ewOQuRg/ljbBTNgi7pr/cDmrG7jaXfNxVG+S51SK9Bme3KR6rgXslZO7PuxuHmscWqdbDxzq9eQT7h7g3JkgU7FtnnZZlLAKt+qfnl9pVecohYhF94uJy11oAyyIdr/RRlJInyTxCA9vdqOrqinsuSxhRA1Eo1UczL8LII6U="
    - secure: "TmJKjUA+/giIEJ8edD0YwWFb7WwTHkVypyaGG0FM2nQJk2Sla9Z+oCbAGUbt8sVG36WSjJBH5G/OvPvLd4im2quHyxn3a776r0BtxUfeTO/Qpr8Sz0jXfPp0rFYmApK6CpPyTT5Iw8BwwBwup6NJD6wJEjIX8nzbbpf/hk+NZxLfHE6Udj6y1AlSimhbg0Bk/mFpdPDsNMudCsKjc8yJQDOh1i5fFiTbzcqeK57VLsRvpZzE+sxJC1TZXK/iYerHd1qrkcbjFNB6GSLFKO107Qn/zfwDdtX2YToVh7EGHJhTXtmaegKqN0e6TkxkMeVYfRlwfme3FXSX1biOg++7WTeSXN8YFfdMwIJHof9IjtE06DhPl2bhCLPJbWkFDClrfP2lODZyZO4K91P0jNgrk2IdCJO4vmWuD1vrQTeg9QcN/s4wJgqzEQRIk9+4OR3CjQob8wYt2l8vuXjvQuKCBocXnMJ+WpA8QmjP8SwiK1e+YMhMxNRQHZZCwPYSr5UhSnA3SnrYg5NjiDj7yVv5RGjY2OLndp8jP2d67HB82fIrRfjd/+ermwgqMhMXf+YHQkrXFwIu5IP219yq80JgbVFTeBet9t+/3Pv7XnLtDa9wibj+ZEeXQ+bYWrnex189h66SWeioOJrzI2PINXnCabPVY+KA7110K3gx3Be83gM="  

go:
  - 1.14.x

before_install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
      # Pull requests are slightly complicated because $TRAVIS_COMMIT_RANGE
      # may include more changes than desired if the history is convoluted.
      # Instead, explicitly fetch the base branch and compare against the
      # merge-base commit.
      git fetch -q origin +refs/heads/$TRAVIS_BRANCH
      changes=$(git diff --name-only HEAD $(git merge-base HEAD FETCH_HEAD))
    else
      changes=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
    fi
    echo "Files changed:"
    echo "$changes"
    if ! echo "$changes" | grep -qvE '(\.md$)|(^(docs|website))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi
  - make go-dependencies
  - sudo apt-get update -y
  - sudo apt-get install software-properties-common -y
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install python3.7 -y
  - sudo apt-get install python3.7-venv -y

jobs:
  include:
    - stage: push-to-quay
      name: "Red Hat Developer - Push to Quay"
      script:
        - make prepare-test-install
    - stage: unit
      name: "Jenkins Operator - unit tests"
      script:
        - make verify
    - stage: e2e
      name: "Backup PVC - e2e"
      script:
        - travis_wait 10 make -C backup/pvc/ docker-e2e UID=$(id -u) GID=$(id -g)
    - stage: e2e
      name: "Jenkins Operator - e2e"
      script:
        - sudo apt-get update
        - sudo apt-get install socat
        - make travis-prepare
        - make build e2e
    - stage: e2e
      name: "Jenkins Operator Helm Chart - e2e"
      script:
        - sudo apt-get update
        - sudo apt-get install socat
        - make travis-prepare
        - make e2e BUILDTAGS=Helm E2E_TEST_SELECTOR='^.*Helm.*$'

cache:
  directories:
    - vendor
    - /home/travis/.minikube/

notifications:
  slack:
    secure: Cke1jTwG9TE7/Oe4dXYPnu3fO49NbrqZX6S75hv6LKwoclTHG2rwjZXEFqpn7g7o1au743lzj12RyeosSWIYA0jN8xU3WHrJApUBq3oOr/oG0Br9jr4EyonWkcwjnpGUZ8UehvYaMZCSRLr2a2ZEShai2ftrYd5CEd066986NEG+Q/dnxhkmWPk7CW37bm5I3duW62mW/QGi3iIzNOSNJtMjbYFP2USHrnEoV2KZ9irKLpBNSyxqVH820FvTUjp+imisP4v27m/dSyuZzbWsc6BGtL+CTwMHMuJVUfTOGpTjW4H9qb42kZO3zFuFdP235Zo+Uxx+OA14n3wNdSgseAEuX6ecMnbglK95ZL/lm5p5wPH/F+05Xu9dh3bqCex9VIjcszzTj/ZJ+mDjMd11nSU++Dbr7e1ynTii+B6tOpiuFGzW5n4yPEjwdrMakohRM+Pukp2fSCQf8YfSutbfTqaYLuTl5UV+kKN4QlAgCyZokSq1tGJ/H21ScI09reJPinM565J9h4Nbkul50XD5pcktBsq9gyLCzJDyG1sNWPOyHV1lG8PsAEGKoCG9+PlP7L48e+QfUuQO9fNM00sjgVHxkXBVqBNMI/UDhlqVgDx4S+WFQivwS894XZNLDwrzXpTfswzMbd08EevyyT1fqbZEIX83V2B0H7A8Oxrb7nM=
