apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-operator
subjects:
- kind: ServiceAccount
  name: jenkins-operator
  namespace: jenkins-testing-test
