# permissions for end users to edit backupconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupconfig-editor-role
rules:
- apiGroups:
  - jenkins.io
  resources:
  - backupconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jenkins.io
  resources:
  - backupconfigs/status
  verbs:
  - get
