# permissions for end users to edit backupworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupworker-editor-role
rules:
- apiGroups:
  - jenkins.io
  resources:
  - backupworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jenkins.io
  resources:
  - backupworkers/status
  verbs:
  - get
