# permissions for end users to edit jenkinsimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkinsimage-editor-role
rules:
- apiGroups:
  - jenkins.io
  resources:
  - jenkinsimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jenkins.io
  resources:
  - jenkinsimages/status
  verbs:
  - get
