apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jenkins.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: Jenkins
    listKind: JenkinsList
    plural: jenkins
    singular: jenkins
  scope: Namespaced
  versions:
    - name : v1alpha2
      served: true
      storage: true
    - name : v1alpha1
      served: true
      storage: false
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jenkinsimages.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: JenkinsImage
    listKind: JenkinsImageList
    plural: jenkinsimages
    singular: jenkinsimage
  scope: Namespaced
  versions:
    - name: v1alpha2
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jenkinsimagebuilds.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: JenkinsImageBuild
    listKind: JenkinsImageBuildList
    plural: jenkinsimagebuilds
    singular: jenkinsimagebuild
  scope: Namespaced
  versions:
  - name: v1alpha2
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cascs.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: Casc
    listKind: CascList
    plural: cascs
    singular: casc
  scope: Namespaced
  versions:
    - name : v1alpha3
      served: true
      storage: true
