apiVersion: jenkins.io/v1alpha2
kind: BackupConfig
metadata:
  name: backupconfig-sample
spec:
  backupOptions:
    config: true
    jobs: true
    plugins: true
  jenkinsRef: jenkins-with-backup-sample
  restartAfterRestore:
    enabled: true
