apiVersion: jenkins.io/v1alpha2
kind: JenkinsImage
metadata:
  name: jenkinsimage-sample
spec:
  from:
    name: jenkins/jenkins
    tag: lts
  plugins:
  - name: kubernetes
  to:
    registry: quay.io/akram
    name: jenkins-for-jim
    tag: latest
    secret: my-secret
