apiVersion: v1
kind: Template
metadata:
  name: jenkins-operator-template
  annotations:
    description: "Jenkins Operator Tempalte used to test Jenkins Operator. Not meant for production purposes."
    tags: "jenkins, ci/cd, devops"
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: jenkins-operator
    namespace: ${JENKINS_OPERATOR_NAMESPACE}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: jenkins-operator
    namespace: ${JENKINS_OPERATOR_NAMESPACE}
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - configmaps
    - secrets
    - serviceaccounts
    - endpoints
    - bindings
    - persistentvolumes
    - limitranges
    verbs:
    - get
    - create
    - update
    - list
    - watch
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    - controllerrevisions
    verbs:
    - get
    - create
    - update
    - list
    - watch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings
    verbs:
    - get
    - create
    - update
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods/portforward
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/exec
    verbs:
    - get
    - create
    - update
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - watch
    - list
    - create
    - patch
  - apiGroups:
    - apps
    resourceNames:
    - jenkins-operator
    resources:
    - deployments/finalizers
    verbs:
    - update
  - apiGroups:
    - jenkins.io
    resources:
    - '*'
    verbs:
    - get
    - create
    - update
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - image.openshift.io
    resources:
    - imagestreams
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - build.openshift.io
    resources:
    - builds
    - buildconfigs
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - route.openshift.io
    resources:
    - routes
    verbs:
    - get
    - create
    - update
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: jenkins-operator
    namespace: ${JENKINS_OPERATOR_NAMESPACE}
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
  - nonResourceURLs:
    - '*'
    verbs:
    - get
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: jenkins-operator
    namespace: ${JENKINS_OPERATOR_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: jenkins-operator
  subjects:
  - kind: ServiceAccount
    name: jenkins-operator
    namespace: ${JENKINS_OPERATOR_NAMESPACE}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: jenkins-operator
    namespace: ${JENKINS_OPERATOR_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: jenkins-operator
  subjects:
  - kind: ServiceAccount
    name: jenkins-operator
    namespace: ${JENKINS_OPERATOR_NAMESPACE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: ${JENKINS_OPERATOR_NAMESPACE}
    name: jenkins-operator
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        name: jenkins-operator
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          name: jenkins-operator
      spec:
        containers:
        - command:
          - jenkins-operator
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.annotations['olm.targetNamespaces']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: jenkins-operator
          image: ${JENKINS_OPERATOR_IMAGE} #quay.io/redhat-developer/openshift-jenkins-operator:0.4.1-ed5de33
          imagePullPolicy: IfNotPresent
          name: jenkins-operator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: jenkins-operator
        serviceAccountName: jenkins-operator
        terminationGracePeriodSeconds: 30     
parameters:
  - name: JENKINS_OPERATOR_NAMESPACE
    description: Namespace in which Jenkins Operator will be deployed
    required: true
  - name: JENKINS_OPERATOR_IMAGE
    description: Test Jenkins Operator with Custom Image
    required: true
    value: "quay.io/redhat-developer/openshift-jenkins-operator:latest"